### ISSUE TITLE
SPIRE agent fails to restart due to SPIRE server shutdown immediately

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#2662]
* **Version**: 1.1.0
* **Platform**: x86_64 GNU/Linux
* **Subsystem**: server

Currently the SPIRE server shutdown immediately when received the SIGNALS.
If the SPIRE server stopped, the agent continuously retry to connect to the server.
In case of the Node Attestor does not accept re-attestation, the SPIRE agent will fail to restart depending on the timing such as the server stopped between store the attested node info into the Datastore and respond attestation result.

To avoid that case, it is better that the server shutdown gracefully, like after received the signal, no new connections will be accepted,  sleep for some grace period, and then do shutdown.

We discuss it on Slack channel.
https://spiffe.slack.com/archives/C7XDP01HB/p1639622657179400

**Comment by azdagron** [comment]
For reference, the servers are stopped [here](https://github.com/spiffe/spire/blob/4b4ffd50174499339bb5b3f1bbd3274258f5e05e/pkg/server/endpoints/endpoints.go#L235) and [here](https://github.com/spiffe/spire/blob/4b4ffd50174499339bb5b3f1bbd3274258f5e05e/pkg/server/endpoints/endpoints.go#L278). Switching them from [Stop](https://pkg.go.dev/google.golang.org/grpc#Server.Stop) to [GracefulStop)[https://pkg.go.dev/google.golang.org/grpc#Server.GracefulStop] will allow outstanding RPCs to complete.

**Comment by hiyosi** [comment]
> GracefulStop()  blocks until all the pending RPCs are finished. 

Normally streaming connections are reconnected with `defaultMaxConnectionAge = 3 * time.Minute`, but do we also need an explicit timeout as a safety measure?

cf.
https://github.com/grpc/grpc-go/issues/2448#issuecomment-437531965

**Comment by evan2645** [comment]
We have had similar problems elsewhere in the codebase and those were solved through two phase commit pattern. IIRC we did this in both the datastore (for agent svid rotation) and on keymanager interface in the agent (for agent key creation and rotation) ... I guess we missed a spot?

> Switching them from Stop to GracefulStop will allow outstanding RPCs to complete.

But we will still have a problem on crash, oom, kill -9 etc right?

**Comment by azdagron** [comment]
Yes, that's true. I think a graceful shutdown thing would be a stopgap for a more complete solution.

**Comment by evan2645** [comment]
> I think a graceful shutdown thing would be a stopgap for a more complete solution.

Yes I think that could be appropriate so long as we don't introduce any unexpected/lengthy shutdown delays

Looking more closely at the code though, I think we may be able to patch this with fairly low overhead? If we can detect a half-attested agent by examining the state of the `SerialNumber` and `NewSerialNumber` fields, then we could modify the agent store host service on SPIRE Server to return NotFound on that condition.

The `AttestAgent` RPC on the Agent API however does not set `NewSerialNumber`, so I think part of the work will be moving that RPC handler over to the two phase flow as well ... but we should be able to patch without a migration?

**Comment by azdagron** [comment]
So your thought is to change AttestAgent to behave like RenewAgent? That would probably work, without a migration. I _think_ it would also still continue to work with a mix of old and new servers... but I haven't spent too much time thinking about it.

That still won't solve it for the join token case, I don't think, as the join token is currently invalidated immediately on use. To fully solve that we'd need to defer the deletion of the join token until the certificate is used for the first time.

**Comment by evan2645** [comment]
> So your thought is to change AttestAgent to behave like RenewAgent? That would probably work, without a migration. I think it would also still continue to work with a mix of old and new servers... but I haven't spent too much time thinking about it.

Yea that was my thought ... and yea I would have to think a little more about the compat implications too

> That still won't solve it for the join token case, I don't think, as the join token is currently invalidated immediately on use. To fully solve that we'd need to defer the deletion of the join token until the certificate is used for the first time.

Eek, yes .. you're right

**Comment by szvincze** [comment]
The same case came up during our tests and the fix of this issue would help us too.
@azdagron , @evan2645 Do you have any idea when this could be fixed?

**Comment by azdagron** [comment]
What version of SPIRE did you see this with @szvincze? The stopgap fix (graceful shut down of plugin RPCs) was merged in #2722 and available in SPIRE 1.2.1.

The more robust fix hasn't been prioritized yet. If you are still seeing this with 1.2.1 that would be helpful to know.

**Comment by szvincze** [comment]
Thanks for the info, @azdagron.

It was definitely before 1.2.1. Haven't checked it on the latest. I will come back if still seeing with 1.2.1.
